현재위치 정보 허용요청 및 위치정보 가져오기
Yapp-17th/Android_1_Client pull request #12
Opened 2020-10-17 09:54 UTC by kimhyebeen

2020-10-20 15:04 UTC, NackUn requested changes
고생하셨습니다. 몇가지만 수정 요청드립니다.

2020-10-20 15:04 UTC, NackUn commented on Picon/.idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
.idea 깃이그노어 설정해주세요~

2020-10-20 15:04 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/helper/LocationHelper.kt
> +    private var locationManager = context.getSystemService(Context.LOCATION_SERVICE) as LocationManager
val로 변경해줘도 괜찮을 것 같습니다.

2020-10-20 15:04 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/helper/LocationHelper.kt
> +        Toast.makeText(context, "권한이 거절되어 정상적인 사용이 어려움", Toast.LENGTH_SHORT).show()
권한이 거절되어 현재 위치 찾기가 불가합니다. 로 문구를 수정해보는 건 어떠실까요?

2020-10-20 15:28 UTC, kimhyebeen commented on Picon/.idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
네! 지금 깃이그노어 파일에 gitignore.io에서 자동생성해준 게 다 쓰여 있는데도 문제가 생기는 것 같아서 따로 .idea/* 추가했습니다~

2020-10-20 15:30 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/helper/LocationHelper.kt
> +    private var locationManager = context.getSystemService(Context.LOCATION_SERVICE) as LocationManager
네 수정했습니다

2020-10-20 15:33 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/helper/LocationHelper.kt
> +        Toast.makeText(context, "권한이 거절되어 정상적인 사용이 어려움", Toast.LENGTH_SHORT).show()
네 그게 더 좋은 것 같아서 수정했습니다😄

2020-10-21 08:47 UTC, NackUn commented
고생하셨습니다!

2020-10-21 08:48 UTC, NackUn commented
고생하셨습니다!

2020-10-21 12:41 UTC, merged