메인화면 - 버튼 배치 및 메뉴 UI 구현
Yapp-17th/Android_1_Client pull request #13
Opened 2020-10-19 01:40 UTC by NackUn

* 메인화면 버튼 배치
* 메뉴 ui 작성

2020-10-19 01:55 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_nav_head.xml
> +                app:layout_constraintTop_toTopOf="@id/map_nav_head_iv_circle_one" />
만약 사용자가 설정한 컬러와 감정이 꼭 5가지가 아니라 그보다 적은 3~4가지일 수도 있을 것 같은데, xml에서 컬러와 감정을 표시하지 않고 해당 LinearLayout에 코드로 유동적으로 view를 추가하는 건 어떻게 생각하세요? 만약 컬러와 감정의 개수가 유동적이라면, 사용자가 저장한 컬러와 감정 데이터 개수에 따라서 유동적으로 추가할 수 있는 게 좋을 것 같아서요~

2020-10-19 02:26 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintEnd_toEndOf="parent" />
화면 클릭했을 때 나타나고 다시 클릭했을 때 없어지는 애니메니션 동작은 아직 적용 안되어 있는 건가요?

2020-10-20 00:42 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                    android:background="@drawable/ic_map_menu" />
map_btn_menu, ic_map_search, ic_map_location 버튼의 경우 width랑 height가 24dp로, 터치 영역이 너무 작습니다.
안드로이드 플랫폼에서 공식적으로 채택하고 있는 meterial design 문서를 보시면, view의 영역은 사용자가 터치할 수 있는 공간을 확보하기 위해서 최소  48dp x 48dp의 크기를 권장하고 있습니다. 그래서 width와 height를 48dp로 늘리고, padding을 사용해서 이미지의 크기를 조절해보시는 게 좋을 것 같습니다~

2020-10-20 00:44 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_nav_head.xml
> +                app:layout_constraintTop_toTopOf="@id/map_nav_head_iv_circle_one" />
이후 색상에 대한 감정 값이 변할 때마다 수정해줄 걸 고려해서 색상 옆 감정을 표현하는 TextView에도 id값이 있으면 좋을 것 같아요.

2020-10-20 00:53 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintTop_toTopOf="parent" />
map_btn_menu, ic_map_search, ic_map_location 버튼의 경우 width랑 height가 24dp로, 터치 영역이 너무 작습니다.
[안드로이드 플랫폼에서 공식적으로 채택하고 있는 meterial design 문서](https://material.io/design/usability/accessibility.html#layout-and-typography)를 보시면, view의 영역은 사용자가 터치할 수 있는 공간을 확보하기 위해서 최소 48dp x 48dp의 크기를 권장하고 있습니다. 그래서 width와 height를 48dp로 늘리고, padding을 사용해서 이미지의 크기를 조절해보시는 게 좋을 것 같습니다~

2020-10-20 00:56 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                    android:background="@drawable/ic_map_menu" />
toolbar부분은 따로 xml로 빼고 include 시켜주어서 분리해주는 것도 좋을 것 같아요~ 옵셔널한 사항이라 꼭 수정하시지는 않아도 됩니당!!

2020-10-20 01:00 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                android:layout_height="match_parent" />
오오 저도 생각해보니 mapFrame id값을 이쪽으로 옮기는 게 맞는 것 같네용😄👍

2020-10-20 01:18 UTC, kimhyebeen requested changes

2020-10-20 01:18 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                    android:background="@drawable/ic_map_menu" />
toolbar부분은 따로 xml로 빼고 include 시켜주어서 분리해주는 것도 좋을 것 같아요~ 옵셔널한 사항이라 꼭 수정하시지는 않아도 됩니당!!

2020-10-20 01:18 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintTop_toTopOf="parent" />
map_btn_menu, ic_map_search, ic_map_location 버튼의 경우 width랑 height가 24dp로, 터치 영역이 너무 작습니다.
[안드로이드 플랫폼에서 공식적으로 채택하고 있는 meterial design 문서](https://material.io/design/usability/accessibility.html#layout-and-typography)를 보시면, view의 영역은 사용자가 터치할 수 있는 공간을 확보하기 위해서 최소 48dp x 48dp의 크기를 권장하고 있습니다. 그래서 width와 height를 48dp로 늘리고, padding과 margin을 사용해서 이미지의 크기와 위치를 조절해보시는 게 좋을 것 같습니다~

2020-10-20 01:18 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintEnd_toEndOf="parent" />
화면 클릭했을 때 버튼들이 나타나고 다시 클릭했을 때 없어지는 애니메니션 동작은 아직 적용 안되어 있는 건가요?

2020-10-20 01:18 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_nav_head.xml
> +                app:layout_constraintTop_toTopOf="@id/map_nav_head_iv_circle_one" />
이후 색상에 대한 감정 값이 변할 때마다 수정해줄 걸 고려해서 색상 옆 감정을 표현하는 TextView에도 id값이 있으면 좋을 것 같다는 생각이 들었는데, 혹시 나중에 데이터바인딩으로 TextView의 텍스트를 수정하게 된다면 id값이 필요 없나용?

2020-10-20 01:18 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                android:layout_height="match_parent" />
오오 저도 생각해보니 mapFrame id값을 이쪽으로 옮기는 게 맞는 것 같네용😄👍

2020-10-20 01:35 UTC, NackUn commented on Picon/app/src/main/res/layout/map_activity.xml
> +                    android:background="@drawable/ic_map_menu" />
음 잘모르겠네요. 예시 혹은 코드 작성해주시면 참고해보겠습니다!

2020-10-20 01:38 UTC, NackUn commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintTop_toTopOf="parent" />
해당 디자인에 경우 재플린에 적혀있는 dp 사이즈를 참고하여서 디자이너의 의견을 들어서 수정을 해야될 것 같습니다^^

2020-10-20 01:38 UTC, NackUn commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintEnd_toEndOf="parent" />
깜빡했네요. 적용하였습니다^^

2020-10-20 01:39 UTC, NackUn commented on Picon/app/src/main/res/layout/map_nav_head.xml
> +                app:layout_constraintTop_toTopOf="@id/map_nav_head_iv_circle_one" />
넵 나중에 viewModel을 넣고 데이터바인딩으로 처리를 한다면 굳이 id 값이 필요하지 않습니다.

2020-10-20 02:04 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintTop_toTopOf="parent" />
엇 아뇨. 터치 영역만 48dp로 늘리고 이미지 크기는 padding을 이용해서 재플린에 있는 24dp 사이즈로 맞추시면 됩니당~ 터치영역만 늘리고 디자인은 그대로 맞추시면 되어요.

2020-10-20 02:08 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                    android:background="@drawable/ic_map_menu" />
대부분 화면과 툴바를 xml로 분리해서 구분합니다. Toolbar부분을 따로 xml파일로 분리하고, 해당 툴바를 포함하는 액티비티xml에 <include/>태그를 사용하면 됩니다. [이 블로그](https://duzi077.tistory.com/166) 보시면 코드참고하시기 편할 것 같아서 찾아왔어요~

2020-10-20 02:10 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_nav_head.xml
> +                app:layout_constraintTop_toTopOf="@id/map_nav_head_iv_circle_one" />
아하 알겠습니다😄

2020-10-20 14:56 UTC, NackUn commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintTop_toTopOf="parent" />
음 패딩을 추가해봤는데 리뷰 부탁드려요. 버튼으로는 이미지에 패딩이 안되서 이미지버튼으로 변경 후 패딩 설정했습니다^^
db5bf75

2020-10-20 15:04 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/map/MapViewModel.kt
> +    val isButtonShown: LiveData<Boolean> get() = _isButtonShown
저 코틀린의 언더바(_)가 뭔지 설명해주실 수 있나요? 처음 접해서 이해하기가 조금 힘들어서요😭
그리고 get() = _isButtonShown을 하게되면 어떻게 되는건지도 설명해주실 수 있나요?

2020-10-20 15:17 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintTop_toTopOf="parent" />
정말 수고하셨습니다:)

2020-10-21 07:13 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintTop_toTopOf="@id/map_btn_add"
애뮬레이터에서 돌려보니까 네이버 마크 바로 위에 현재위치 마커가 뜨는데 네이버 마커랑 조금 떼어져 있는게 보기 더 좋지 않을까용??

2020-10-21 08:44 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/map/MapViewModel.kt
> +    val isButtonShown: LiveData<Boolean> get() = _isButtonShown
음 코틀린의 컨벤션입니다. private 형을 _를 붙여서 표현하고
외부에서는 isButton으로 접근을 합니다. get() 만 있어서 외부에서 접근 시 _isButtonShown 이 불려지며 외부에서 set을 할 수는 없습니다. 게터, 세터 처럼 생각하시면 되세요^^
https://kotlinlang.org/docs/reference/coding-conventions.html
Names for backing properties

2020-10-21 08:46 UTC, NackUn commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintTop_toTopOf="@id/map_btn_add"
원래는 constraint 를 네이버 마크랑 붙여볼려고 했는데 어떻게 해야될 지 모르겠어서 일단 add에 맞춰서 표시를 해줬는데... 한 번 다시 살펴보겠습니다.

2020-10-21 09:01 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/map/MapViewModel.kt
> +    val isButtonShown: LiveData<Boolean> get() = _isButtonShown
아하 덕분에 몰랐던 걸 알게 되었어요ㅎㅎㅎ

2020-10-21 13:45 UTC, NackUn commented on Picon/app/src/main/res/layout/map_activity.xml
> +                    android:background="@drawable/ic_map_menu" />
@kimhyebeen 후에 툴바를 재사용할 때 리팩토링하도록 해요~

2020-10-21 13:56 UTC, NackUn commented on Picon/app/src/main/res/layout/map_activity.xml
> +                app:layout_constraintTop_toTopOf="@id/map_btn_add"
93de841
현재위치 버튼 위치 수정했습니다.(임의로 배치해놨어요~)

2020-10-21 14:11 UTC, kimhyebeen approved these changes

2020-10-21 14:12 UTC, merged