Setting과 커스텀 화면의 메인 UI 구현
Yapp-17th/Android_1_Client pull request #20
Opened 2020-10-22 11:10 UTC by kimhyebeen

* 구현 과정에서 MVVM을 고려하지 못했던 것 같은데 이대로 구현해도 괜찮은지 확인 필요합니다.

2020-10-28 02:09 UTC, NackUn requested changes
고생하셨습니다!
xml id 정리 부탁드려요!

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/AndroidManifest.xml
> +        <activity android:name=".presentation.map.MapActivity">
이렇게 상위 패키지 생략해도 되는군요! 처음 알았습니다. 감사합니다!

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/res/layout/app_bar_basic.xml
> +        android:src="@drawable/ic_back" />
drawable 이름은 (ic)_(presentation package)_(설명) 이렇게 하는 건 어떻게 생각하세요?
(회사 프로젝트에서 안드로이드 컨벤션을 사용하지 않고 있어서 혼자서 쓰는 컨벤션입니다. 의견주시면 감사하겠습니다^^)

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/res/layout/setting_activity.xml
> +            android:id="@+id/settingFrame"
xml id는 카멜케이스보다는 스네이크 케이스를 자주 사용하는 것으로 알고 있습니다^^

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/res/layout/setting_activity.xml
> +            android:id="@+id/appBarInclude"
혹시 어디의 AppBar 인지 알 필요가 없을까요?

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/base/BaseFragment.kt
> +    protected lateinit var rootView: View
rootView는 지울 수 있을 것 같아요

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/customview/CustomEmotionItem.kt
> +open class CustomEmotionItem: ConstraintLayout {
나중에 리사이클러뷰 아이템으로 변경해보죠!

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/CustomEmotionFragment.kt
> +    // TODO ("BaseFragment로 바꾸기")
요거 todo 해주세요~

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +        val finishActivity: (View) -> Unit = {
같은 ViewModel을 공유하고 있으니 ViewModel쪽에 데이터를 관찰하는 것으로 finish 여부를 판별해도 될 것 같아요

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +                    NavTypeStringSet.CustomEmotion.type -> CustomEmotionFragment()
커스텀이모션프래그먼트도 종료 구현 부탁드려요^^

2020-10-28 02:09 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/SettingFragment.kt
> +    override val vm: NavViewModel by viewModels()
네비게이션 뷰모델을 세팅에서 사용하려면 네비게이션에서 뷰모델을 넘겨주는건 어떻게 생각하세요?

2020-10-28 07:57 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/app_bar_basic.xml
> +        android:src="@drawable/ic_back" />
음.. 말씀해주신 양식대로 바꿔볼까 생각해봤는데, 해당 drawable 소스가 한 곳에서 사용되는 게 아니라 여러 화면에서 사용되어서 presentation package에 뭐가 들어가야 할지 모르겠어요.

2020-10-28 08:13 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/setting_activity.xml
> +            android:id="@+id/settingFrame"
네 수정했습니다~

2020-10-28 08:28 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/setting_activity.xml
> +            android:id="@+id/appBarInclude"
제가 구현 중에 없앤 코드라서 수정 안해도 될 것 같습니다~

2020-10-28 08:28 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/base/BaseFragment.kt
> +    protected lateinit var rootView: View
네😄

2020-10-28 08:28 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/customview/CustomEmotionItem.kt
> +open class CustomEmotionItem: ConstraintLayout {
네😄

2020-10-28 08:28 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/CustomEmotionFragment.kt
> +    // TODO ("BaseFragment로 바꾸기")
네~

2020-10-28 09:03 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +                    NavTypeStringSet.CustomEmotion.type -> CustomEmotionFragment()
일단 종료 기능은 구현 했습니다. 다이얼로그 띄우는 기능은 이번 UI 구현 부분 PR 머지 하고 나서 추후에 세부 기능 구현할 때 하겠습니다~

2020-10-28 09:04 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/SettingFragment.kt
> +    override val vm: NavViewModel by viewModels()
NavActivity에서 fragment가 가져오도록 수정했습니다~

2020-11-02 10:01 UTC, NackUn commented on Picon/app/src/main/res/layout/app_bar_basic.xml
> +        android:src="@drawable/ic_back" />
음 여러 곳에서 사용하면 그냥 저렇게 사용해도 될 것 같습니다!

2020-11-02 10:02 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +                    NavTypeStringSet.CustomEmotion.type -> CustomEmotionFragment()
넵!!

2020-11-02 10:35 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +        val finishActivity: (View) -> Unit = {
같은 NavActivity여도 fragment마다 viewmodel의 finishFlag가 달라질때 해주는 행동이 달라서 Activity가 아닌 Fragment에서 ViewModel의 데이터를 관찰하는 것으로 바꿔주었습니다~

2020-11-02 13:04 UTC, NackUn requested changes
ViewModel을 공유해서 사용해보면 어떨까요?
https://thdev.tech/androiddev/2020/07/13/Android-Fragment-ViewModel-Example/

2020-11-02 13:04 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/customview/CustomEmotionItem.kt
> +        view.emotion_item_tv.text = emotionText
View binding으로 이렇게 사용할 수 있는건가요??

2020-11-02 13:33 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/customview/CustomEmotionItem.kt
> +        view.emotion_item_tv.text = emotionText
음.. view binding이라기보다는 inflate한 view에 접근한다고 하는 게 더 맞지 않을까요..? 커스텀뷰에 inflate하는 view 객체의 TextView에 접근을 했다는 말이 더 맞는 것 같은데 그게 view binding이랑 같은 개념인가요? 제가 아직 view binding이라는 개념이 잡혀있지가 않아서 잘 모르겠어요..

2020-11-02 13:43 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/customview/CustomEmotionItem.kt
> +        view.emotion_item_tv.text = emotionText
음 잘모르겠네요..ㅠ 좀 더 공부해야겠습니다! (아래 블로그에 관련 내용이 있는 것 같습니다 ㅎㅎ)
https://medium.com/@charlezz/view-binding-살펴보기-df3526d909a7

2020-11-02 14:59 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +    private var type: String? = null
혹시 type을 전역으로 빼신 이유가 있으신가요??

2020-11-02 15:01 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +    private var type: String? = null
finishFlag를 observe할 때, fragment에 따라서 기능이 다른 게 있어서 구분해주려고 따로 뺐어요

2020-11-02 15:28 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +    private var type: String? = null
좋은 방법인지는 모르겠지만 finishFlag 를 String 형으로 Observe 하는게 어떻까요!? 아니면 ViewModel 변수를 isFinish, finishFlag 두개를 만드는건 어떨까요?

2020-11-02 15:34 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +    private var type: String? = null
음.. finishFlag를 String형으로 한다는건 예를들어 어떤 걸 말하는 걸까요? 그래도 fragment에 따라 activity에서 다르게 처리해줘야 하는 건 같지 않나용?

2020-11-02 15:39 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +    private var type: String? = null
앗 지금은 finishFlag가 Boolean 형으로 ViewModel에 있잖아요?
그걸 String으로 변경하고 Click도 각각 String에 키를 넘겨주는 걸로 변경해서 Observe에 String을 비교해서 각각의 finish를 대응해주면 될 것 같은데 어떻게 생각하시나요??

2020-11-02 15:48 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/nav/NavActivity.kt
> +    private var type: String? = null
음 제가 맞게 이해한 건지 모르겠는데, 그럼 intent로 넘겨받은 type은 activity에서 attach할 fragment를 구분하는 데에만 사용하고, 그 타입을 view model에 LiveData<String>에 저장하고, 다시 저장한 그 string에 따라 activity에서 구분해서 처리하게 되는 건가요?
그럼 그냥 activity에서 type으로 구분하는 거랑 다른 게 없는 것 같은데 제가 잘못 이해한건가요?ㅠ.ㅠ

2020-11-02 16:37 UTC, NackUn approved these changes

2020-11-02 16:38 UTC, merged