통신테스트
Yapp-17th/Android_1_Client pull request #24
Opened 2020-11-02 10:00 UTC by NackUn

* 통신테스트

2020-11-02 10:19 UTC, kimhyebeen commented on Picon/app/src/main/AndroidManifest.xml
>      <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
통신하는데에 인터넷 권한은 필요 없는지 궁금합니다

2020-11-02 10:20 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/map/MapActivity.kt
> +        }
나중에 이 부분도 xml에서 데이터바인딩으로 onClick 설정하는 건 어떻게 생각하시나요?

2020-11-02 10:22 UTC, kimhyebeen approved these changes
통신 테스트 예제를 잘 작성해주셔서 이해하는 데 편했어요. 수고하셨습니다!!
코멘트는 지금 당장 고쳐야 할 것이 아닌 궁금증이라 답변만 해주시면 될 것 같아요~

2020-11-02 13:06 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/presentation/map/MapActivity.kt
> +        }
음 저는 onClick은 View에서 작업하는데 원하시면 데이터바인딩으로 처리해도 좋습니다!

2020-11-02 13:06 UTC, NackUn commented on Picon/app/src/main/AndroidManifest.xml
>      <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
어..그러게요 ㅋㅋㅋ 인터넷권한이 필요할꺼 같은데 테스트가 되서 음..인터넷 권한 추가하겠습니다!

2020-11-02 13:48 UTC, NackUn commented on Picon/app/src/main/AndroidManifest.xml
>      <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
추가했습니다
9674889

2020-11-02 14:44 UTC, kimhyebeen commented on Picon/app/src/main/AndroidManifest.xml
>      <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
네~

2020-11-02 14:44 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/map/MapActivity.kt
> +        }
아니예요 그럼 편하신대로 하셔도 됩니당

2020-11-03 00:20 UTC, kimhyebeen requested changes

2020-11-03 00:20 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/presentation/map/MapViewModel.kt
> +    fun createPost() {
생각해보니 저희 Post를 지우는 작업도 필요하지 않나요? 하나씩 지우는 거랑 한꺼번에 모두 지우는 거요!

2020-11-04 04:56 UTC, merged