프로젝트 기본 작업 구축
Yapp-17th/Android_1_Client pull request #7
Opened 2020-09-29 11:18 UTC by kimhyebeen

* 안드로이드 프로젝트 생성
* 지도 dependency 추가
* MainActivity에 지도 적용

2020-10-02 05:43 UTC, NackUn requested changes
고생하셨습니다. 리뷰가 늦어서 죄송합니다.
gitignore 설정을 조금 더 추가해주시면 좋을 것 같습니다.
또한 키값을 깃이그노어에 넣어주시면 해당 프로젝트를 실행해보는게 어려울 것 같습니다.

2020-10-02 05:43 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
BaseActivity를 만들고 BaseActivity를 상속받는 BaseMapActivity를 만드시는 건
어떻게 생각하시나요?

2020-10-02 05:43 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +    @LayoutRes private val layoutId: Int = R.layout.activity_main
layoutId에 값을 주지않고 외부에서 상속할때 넣어주는 식으로 하는게 어떨까요?

2020-10-02 05:43 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +        setContentView(layoutId)
데이터바인딩을 사용할 수 있으시면 사용해보는 것도 좋을 것 같습니다.

2020-10-02 05:53 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
저는 네이버 맵 api를 가져와서 띄우는 역할을 BaseMapActivity로 두고 MainActivity에서 BaseMapActivity를 상속받도록 했었는데, 말씀하신 BaseActivity와 BaseMapActivity은 그럼 어떤 역할을가지나요?

2020-10-02 05:56 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
그리고 gitignore 설정을 조금 더 추가하라는 말이 뭔지 모르겠어요...
키값은 제가 키값 담은 파일을 따로 드릴테니 그걸로 그냥 실행해보는건 어떠신가요? 알고있기론 깃허브에 키값이 올라가면 안되는 걸로 알고 있어서요~

2020-10-02 05:57 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +        setContentView(layoutId)
네 데이터바인딩 사용해서 다시 바꿔보겠습니당

2020-10-02 06:00 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
넵 제가 생각한 구조는 모든 엑티비티들이 상속을 받는 BaseAcitivity를 만들고 해당 BaseActivity는 데이터바인딩의 역할과 뷰모델을 강제해주는 역할을 해주셨으면 좋겠습니다.
또한 BaseMapAcivity는 그런 BaseActivity를 상속받으며 Activity에 Map 이 필요한 경우에 사용하면 좋을 것 같아서 생각해보았습니다

2020-10-02 06:02 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
gitignore 설정에 추가해달라는 말은 필요없는 파일까지 전부 올라가 있는 거 같아서 말씀드려봤습니다ㅎㅎ
해당 사이트에서 android, androidStudio 정도만 검색하셔서 복사하셔도 좋을 것 같습니다.
gitignore.io 란 사이트로 gitignore 초기 설정할 때 좋은 것 같습니다. 참고만해주세요 ㅎㅎ
https://www.toptal.com/developers/gitignore

2020-10-02 06:04 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
혜빈님 말씀처럼 키값은 안올리는게 맞는 것 같은데 slack이나 구글드라이브로 공유할 수 있는 걸 만들어주시면 좋을 것 같아요.
저말고 서버 분들 혹은 Yapp에 다른 분들도 확인하실 수 있게 하는게 어떤가 해서 말씀드려봤습니다.

2020-10-02 06:29 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
음.. 제가 방금 BaseActivity에 데이터바인딩과 뷰모델을 강제하는 역할을 넣어서 만들어보려고 했는데, 강제성을 주려면 인터페이스로 만들어서 강제성을 주던가 혹은 추상 클래스로 만들어서 확장시키도록 하던가 해야 할 것 같고 거기서 데이터바인딩 변수와 뷰모델 변수를 선언해야할 것 같다고 생각이 들었습니다. 

근데 생각해보니 데이터바인딩 변수나 뷰모델 변수를 선언하려면 ActivityMainBinding처럼 액티비티 이름에서 자동으로 생성되는 타입과 뷰모델 이름을 알고 있어야 하는데 뷰모델이 하나면 그냥 뷰모델 이름 정해서 타입으로 선언해주면 상관 없지만, 데이터바인딩의 경우 앞으로 생성되는 액티비티에 따라 타입이 달라질 것 같아서요. 

혹시 제가 생각하면서 놓친 부분이 있거나, 어떻게 강제성을 줄지 생각 있으시면 조금 알려주실 수 있을까요?

2020-10-06 23:43 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
저도 스터디하면서 배운 건데 한 번 코드 확인해보시구 질문 있으시면 말씀해주세요 ㅎㅎ

https://github.com/NackUn/RxJavaStudy/blob/coroutine-NackUn/StudyFirst/app/src/main/java/sample/nackun/com/studyfirst/presentation/base/BaseActivity.kt

수정한 부분 커밋 날려주시면 확인하고 추가 피드백 드리겠습니다.

2020-10-07 00:23 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
네 알겠습니다! 참고해서 수정하고 다시 PR 날리겠습니다~

2020-10-07 05:10 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +abstract class BaseMapActivity(
링크 참고해서 수정했습니다! 커밋확인해주세요~

2020-10-07 06:47 UTC, NackUn requested changes

2020-10-07 06:47 UTC, NackUn commented on .gitignore
> +Picon/app/src/main/java/com/yapp/picon/SecretKeySet.kt
해당 부분은 커밋을 분리해주셔도 좋을 것 같습니다.

2020-10-07 06:47 UTC, NackUn commented on Picon/app/src/main/res/layout/activity_main.xml
> +        <variable
activity는 어떤 용도로 가지고 있는건가요?

2020-10-07 07:00 UTC, NackUn requested changes
viewBinding 을 사용하셨는데 저도 잘몰라서 어떤 점에서 사용하신 걸까요??

2020-10-07 07:00 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +    private val mapFrameId = R.id.mapFrame
BaseMapActivity니깐 Map을 인자로 받거나 abstract로 만들어도 괜찮지 않을까요?

2020-10-07 07:00 UTC, NackUn commented on Picon/app/src/main/res/layout/activity_main.xml
>          <FrameLayout
Fragment 대신 FrameLayout 사용 한 이유가 무엇인지 궁금합니다.

2020-10-07 11:11 UTC, kimhyebeen commented on .gitignore
> +Picon/app/src/main/java/com/yapp/picon/SecretKeySet.kt
헉 커밋에 api키 파일이 들어간지 몰랐어요ㅠ 빼겠습니당

2020-10-07 11:11 UTC, kimhyebeen commented on .gitignore
> +Picon/app/src/main/java/com/yapp/picon/SecretKeySet.kt
네 앞으로 주의하겠습니다

2020-10-07 11:13 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/activity_main.xml
>          <FrameLayout
아 지도 위에 여러 아이콘버튼을 띄워야 한다는 생각에 FrameLayout을 사용했던 것 같은데, Fragment로 바꾸는게 나을까요?

2020-10-07 11:13 UTC, kimhyebeen commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +    private val mapFrameId = R.id.mapFrame
네 수정하겠습니다~

2020-10-07 11:19 UTC, kimhyebeen commented on Picon/app/src/main/res/layout/activity_main.xml
> +        <variable
앗 데이터바인딩 예제 보면서 하다보니 필요 없는 코드까지 들어간 것 같습니다. 지우고 commit 다시 날리겠습니당

2020-10-07 13:42 UTC, NackUn requested changes

2020-10-07 13:42 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
> +    private val mapFrameId: Int
해당 부분 인자를 2개로 하는 건 어떨까요? activity에 사용할 xml과 map Frame id 2개를 받고 xml을 BaseActivity에서 사용하는 거죠~

2020-10-07 13:42 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
>          super.onCreate(savedInstanceState)
binding.activity = this 이것도 지워도 될 것 같습니다

2020-10-07 13:43 UTC, NackUn commented on Picon/app/src/main/java/com/yapp/picon/BaseMapActivity.kt
>          super.onCreate(savedInstanceState)
16번째 라인인데 안눌러져가지고... 16번째 라인 확인해주세요~

2020-10-10 05:27 UTC, NackUn commented on Picon/app/src/main/res/layout/activity_main.xml
>          <FrameLayout
이건 생각을 해보는게 좋을 것 같네요 ㅎㅎ

2020-10-10 05:30 UTC, NackUn approved these changes
고생하셨습니다!

2020-10-10 09:10 UTC, merged